name: "Split repositories"

on:
  push:
    branches: ~
  workflow_dispatch: ~

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Debug global variables
        run: |
          echo "::group::unix env"
          env | sort
          echo "::endgroup::"
          echo "::group::github"
          echo '${{ toJson(github) }}'
          echo "::endgroup::"
          echo "::group::env"
          echo '${{ toJson(env) }}'
          echo "::endgroup::"
          echo "::group::job"
          echo '${{ toJson(job) }}'
          echo "::endgroup::"
          echo "::group::steps"
          echo '${{ toJson(steps) }}'
          echo "::endgroup::"
          echo "::group::strategy"
          echo '${{ toJson(strategy) }}'
          echo "::endgroup::"
          echo "::group::matrix"
          echo '${{ toJson(matrix) }}'
          echo "::endgroup::"
          echo "::group::needs"
          echo '${{ toJson(needs) }}'
          echo "::endgroup::"
          echo "::group::inputs"
          echo '${{ toJson(inputs) }}'
          echo "::endgroup::"
          echo '${{ secrets.MY_SECRET }}'
